# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BFit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BFit
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'DropDown'
  pod 'SCLAlertView'
  pod 'lottie-ios'
  
end
